django/website/urls.py
from django.conf.urls import include, url
# from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from custom_organizations.backends.invitation_backend import InvitationBackend

import logframe.urls
import api.urls


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('contacts.auth_urls')),
    url(r'^accounts/sign-up/', include('registration.backends.default.urls')),
    url(r'^orgs/', include('custom_organizations.urls')),
    url(r'^orgs/', include('organizations.urls')),
    url(r'^orgs/invitations/', include(InvitationBackend().get_urls())),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include(api.urls)),
    url(r'^contacts/', include('contacts.org_independent_urls')),
    url(r'^(?P<org_slug>[\w\d_-]+)/contacts/', include('contacts.urls')),
    url(r'^export/', include('export.urls')),
    url(r'', include(logframe.urls)),

    # This requires that static files are served from the 'static' folder.
    # The apache conf is set up to do this for you, but you will need to do it on
    # dev
    url(r'favicon.ico', RedirectView.as_view(
        url='{0}images/favicon.ico'.format(settings.STATIC_URL), permanent=True)),

    # LAST - redirect from root URL to the logframe app
    # url(r'^$', RedirectView.as_view(url=reverse_lazy('logframe-overview', args=(1,)))),
    url(r'', include('dashboard.urls')),
]

django/website/contacts/models.py
import os.path

from django.db.models import (
    CharField, TextField, EmailField,
    FileField, DateTimeField, BooleanField,
    ImageField, ForeignKey, OneToOneField, Model
)
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin, Permission)
from django.utils import timezone
from django.utils.deconstruct import deconstructible
from django.utils.six import python_2_unicode_compatible

from main.upload_handler import UploadToHandler
from .countries import COUNTRIES, NATIONALITIES


def get_user_fields(instance):
    return (instance.business_email, instance.last_name, instance.first_name)


@deconstructible
class PictureUploadHandler(object):
    path_base = ''

    def __init__(self, path_base):
        self.path_base = path_base

    def __call__(self, instance, filename):
        name = "_".join([instance.last_name, instance.first_name]).strip('_')
        prefix = name if name else instance.business_email
        new_filename = "{0}_{1}".format(prefix, filename)
        new_path = os.path.join(self.path_base, new_filename)
        return new_path


# Managers
class UserManager(BaseUserManager):
    def _create_user(self, business_email=None, password=None,
                     is_active=True, is_staff=False, is_superuser=False,
                     **extra_fields):
        now = timezone.now()
        if not business_email:
            raise ValueError('The given business_email must be set')
        email = UserManager.normalize_email(business_email)
        user = self.model(business_email=email, is_staff=is_staff,
                          is_active=is_active, is_superuser=is_superuser,
                          last_login=now, date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, business_email=None, password=None, **extra_fields):
        return self._create_user(business_email, password, **extra_fields)

    def create_superuser(self, business_email, password, **extra_fields):
        return self._create_user(business_email, password, is_staff=True,
                                 is_superuser=True, **extra_fields)


# Models
class User(AbstractBaseUser, PermissionsMixin):
    # Account info
    business_email = EmailField(unique=True)
    is_staff = BooleanField(
        verbose_name='staff status',
        default=False,
        help_text=('Designates whether the user can log into this admin '
                   'site.'))
    is_active = BooleanField(
        verbose_name='active',
        default=True,
        help_text=('Designates whether this user should be treated as '
                   'active. Unselect this instead of deleting accounts.'))
    date_joined = DateTimeField(default=timezone.now)

    # general contact information
    first_name = CharField(max_length=50)
    last_name = CharField(max_length=50)

    # Managers and book-keeping

    USERNAME_FIELD = 'business_email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserManager()

    def get_full_name(self):
        return u"{0} {1}".format(self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

    def __unicode__(self):
        return self.get_full_name()

    @property
    def email(self):
        return self.business_email

    @property
    def preferences(self):
        try:
            preferences = self._preferences
        except UserPreferences.DoesNotExist:
            preferences = UserPreferences.objects.create(user=self)
        return preferences


class UserPreferences(Model):
    user = OneToOneField(User, related_name='_preferences')
    last_viewed_logframe = ForeignKey('logframe.LogFrame', null=True)
    last_viewed_organization = ForeignKey('organizations.Organization', null=True)

@python_2_unicode_compatible
class NameOnlyPermission(Permission):
    class Meta:
        proxy = True

    def __str__(self):
        return "Can {0}".format(self.name.lower())

django/website/main/templates/base.html
{% load assets %}
{% load settings_value %}
{% load i18n %}
{% load waffle_tags %}

<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title>{% settings_value "SITE_NAME" %} MIS {% block title %}{% endblock %}</title>
    {% block extra_media %}
    {% endblock %}
    {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
    <script>window.Aptivate = {};</script>
</head>
<body{% block body_attrs %}{% endblock %}>
    <div class="body"> {# Created because ui.jquery really doesn't like sized <body> #}

    <header class="page-header">
       <h1 class="logo"><a href="/"><img src="{% settings_value "SITE_LOGO" %}" /><span class="site-name">{% settings_value "SITE_NAME" %}</span></a></h1>
       <nav class="main-navigation">
        {% block organization_switching_form %}
        {% if request.user and request.user.is_authenticated and request.user.organizations_organization.exists %}
		<form id="organizations-switch" action="{% url "switch-organizations" %}" method="post">{% csrf_token %}
            <select id="organizations-switch-select" name="organization" onchange="this.form.submit();"{% if organization_list|length == 1 and not perms.organizations.add_organization %} disabled="disabled"{% endif %}>
                {% for organization in organization_list %}<option value="{{ organization.id }}"{% if request.user.preferences.last_viewed_organization == organization %} selected="selected"{% endif %}>{{ organization.name }}</option>{% endfor %}
                {% if perms.organizations.add_organization %}
                    <option value="-1">{% trans "Create a new Organization" %}</option>
                {% endif %}
            </select>
        </form>
        {%  endif %}
        {% endblock organization_switching_form %}

        {% block logframe_switching_form %}
        {% if request.user and request.user.is_authenticated and request.user.preferences.last_viewed_organization and logframe_list %}
        <form id="logframes-switch" action="{% url "switch-logframes" request.user.preferences.last_viewed_organization.slug %}" method="post">{% csrf_token %}
            <select id="logframes-switch-select" name="logframe" onchange="this.form.submit();"{% if logframe_list|length == 1 and not perms.logframe.add_logframe %} disabled="disabled"{% endif %}>
            	{% for logframe in logframe_list %}<option value="{{ logframe.id }}"{% if request.user.preferences.last_viewed_logframe == logframe %} selected="selected"{% endif %}>{{ logframe.name }}</option>{% endfor %}
        {% if perms.logframe.add_logframe %}
            	<option value="-1">{% trans "Create a new Logframe" %}</option>
            	{% endif %}
			</select>
		</form>
		{% endif %}
		{% endblock logframe_switching_form %}

        {% if request.user and request.user.is_authenticated %}
         <div class="account-links-auth"><a href="{% url "logout" %}">{% trans "Log out" %}</a></div>
         {% if request.user.preferences.last_viewed_logframe %}
            <div class="navigation-link"><a href="{% url "logframe-dashboard" request.user.preferences.last_viewed_logframe.organization.slug request.user.preferences.last_viewed_logframe.slug %}" id="nav-dashboard">{% blocktrans with request.user.preferences.last_viewed_logframe.name as logframe_name %}{{ logframe_name }} Overview{% endblocktrans %}</a></div>
         {% endif %}
         <div class="account-links-profile"><span>{% trans "Logged in as:" %} </span><a href="{% url "personal_edit" %}">{{ request.user.get_full_name|default:request.user.business_email }}</a></div>
        {% else %}
            <div class="account-links-auth"><a href="{% url "login" %}">{% trans "Log in" %}</a></div>
            <div class="account-links-auth"><a href="{% url "registration_register" %}">{% trans "Register" %}</a></div>
            {% endif %}
            {% if request.user and request.user.is_authenticated %}
                {% if perms.contacts.add_user and request.user.organizations_organization.exists %}
            <div class="navigation-link" id="nav-people"><a href="{% url "contact_list" request.user.preferences.last_viewed_organization.slug %}">{% trans "People" %}</a></div>
                {% endif %}
            {% endif %}
        </nav>
    </header>
    <div class="content-box">
        {% block main_menu %}
        {% endblock main_menu %}

        {% if messages %}
        <div class="messagelist">
            {% for message in messages %}
            <div class="no-select message message-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <div class="content" id="wrapper">
            {% block content %}{% endblock %}
        </div>
    </div>

    <footer>
        <div class="siteinfo"><p>Built by <a href="http://aptivate.org">Aptivate</a></p></div>
    </footer>
    </div> {# div.body #}
    {% block post_footer %}{% endblock %}
    {% block wafflejs %}
    <script>
    {% wafflejs %}
    </script>
    {% endblock %}
    {% if deploy_env == "staging" or deploy_env == "production" %}
    <script data-main="{{ STATIC_URL }}dist/logframe.min.js" src="{{ STATIC_URL }}js/lib/require.js"></script>
    {% else %}
    <script data-main="{{ STATIC_URL }}js/main.js" src="{{ STATIC_URL }}js/lib/require.js"></script>
    {% endif %}
</body>
</html>

django/website/main/templates/form_snippet.html
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            <div class="pure-control-group">
                <label>
                    <span {{ field.row_attrs }}>{{field.label}}</span>
                    {% if field.help_text %}<span class="help-text">{{ field.help_text|safe }}</span>{% endif %}
                </label>
                {{ field }}
                {% if field.errors %}<span class="field-errors clearfix">{{ field.errors }}</span>{% endif %}
            </div>
        {% endfor %}

django/website/main/templates/main_aside.html
{% extends "base.html" %}

{% block content %}
<section role="main" class="main-column">
    {% block main_content %}{% endblock %}
</section>
<aside class="sidebar">
    {% block sidebar %}{% endblock %}
</aside>
{% endblock %} {# content #}

django/website/main/templates/main_only.html
{% extends "base.html" %}

{% block content %}
<section role="main" class="main-column">
    {% block main_content %}{% endblock %}
</section>
{% endblock %} {# content #}